# Generated by Django 5.0.1 on 2024-02-03 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeType',
            fields=[
                ('change_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('change_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_name', models.CharField(max_length=50)),
                ('component_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_name', models.CharField(max_length=50)),
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('schedule_type', models.CharField(max_length=10)),
                ('schedule_value', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('user_password', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5)])),
                ('user_mode', models.CharField(choices=[('A', 'administrator'), ('B', 'inspector')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeSeeker',
            fields=[
                ('ChangeSeeker_id', models.AutoField(primary_key=True, serialize=False)),
                ('Changed_activity_id', models.IntegerField()),
                ('position_number', models.IntegerField(default=0)),
                ('change_activity_type_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liveData.changetype')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_issued_date', models.DateField(default=django.utils.timezone.now)),
                ('activity_description', models.TextField()),
                ('activity_component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.component')),
                ('activity_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.machine')),
                ('activity_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.schedule')),
                ('activity_status_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liveData.status')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.activity')),
                ('task_assign_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.users')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_text', models.TextField()),
                ('report_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveData.activity')),
                ('report_user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liveData.users')),
            ],
        ),
    ]
