# Generated by Django 5.0.1 on 2024-02-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0003_schedule_schedule_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liveData.users'),
        ),
    ]
