# Generated by Django 5.0.1 on 2024-02-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0004_activity_activity_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='liveData.users'),
        ),
    ]
