# Generated by Django 5.0.1 on 2024-02-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0006_alter_task_task_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='liveData.users'),
        ),
    ]
