# Generated by Django 5.0.1 on 2024-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0007_alter_activity_activity_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_audio',
            field=models.FileField(blank=True, null=True, upload_to='audios'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
