# Generated by Django 5.0.1 on 2024-03-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0009_remove_report_report_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
