# Generated by Django 5.0.1 on 2024-03-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0010_report_report_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_submitted',
        ),
    ]
