# Generated by Django 5.0.1 on 2024-03-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0011_remove_report_report_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='logged',
            field=models.BooleanField(default=False),
        ),
    ]
