# Generated by Django 5.0.1 on 2024-04-02 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0013_users_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_last_reported',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 5, 14, 56, 783603, tzinfo=datetime.timezone.utc)),
        ),
    ]
