# Generated by Django 5.0.1 on 2024-04-02 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0014_activity_activity_last_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_schedule_value',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_last_reported',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 7, 46, 31, 673368, tzinfo=datetime.timezone.utc)),
        ),
    ]
