# Generated by Django 5.0.1 on 2024-04-02 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0015_activity_activity_schedule_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_last_reported',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 8, 16, 58, 831114, tzinfo=datetime.timezone.utc)),
        ),
    ]
