# Generated by Django 5.0.1 on 2024-04-16 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveData', '0016_alter_activity_activity_last_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_last_reported',
            field=models.DateField(default=datetime.datetime(2024, 4, 16, 5, 29, 26, 831453, tzinfo=datetime.timezone.utc)),
        ),
    ]
